drivers: i2c_nios2: device config_info content mutated
The device config_info structure is intended to be read-only, and so
the generic pointer stored in struct device is a pointer-to-const.
The i2c_nios2 driver removes this qualifier when casting the pointer to
the device-specific type.  This removal is a violation of MISRA 11.8
as it evokes undefined behavior.

When the qualifier is preserved the driver does not build, because it
modifies the object content at runtime.  Consequently the fix for this
driver has been removed from #25248.

https://github.com/pabigot/zephyr/commits/nordic/issue/24745d provides
the changes necessary to preserve const correctness.  When applied it
produces the following diagnostic, among others:

```
home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/i2c/i2c_nios2.c: In function 'i2c_nios2_configure':
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/i2c/i2c_nios2.c:36:13: error: passing argument 1 of 'k_sem_take' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   36 |  k_sem_take(&config->sem_lock, K_FOREVER);
      |             ^~~~~~~~~~~~~~~~~
In file included from ../../../../../../../include/kernel.h:5421,
                 from ../../../../../../../include/init.h:11,
                 from ../../../../../../../include/device.h:22,
                 from ../../../../../../../include/drivers/i2c.h:23,
                 from /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/i2c/i2c_nios2.c:10:
zephyr/include/generated/syscalls/kernel.h:746:45: note: expected 'struct k_sem *' but argument is of type 'const struct k_sem *'
  746 | static inline int k_sem_take(struct k_sem * sem, k_timeout_t timeout)
      |                              ~~~~~~~~~~~~~~~^~~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/i2c/i2c_nios2.c:55:22: error: passing argument 1 of 'alt_avalon_i2c_init' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   55 |  alt_avalon_i2c_init(&config->i2c_dev);
      |                      ^~~~~~~~~~~~~~~~
```

The driver must be updated to resolve this and incorporate the change
from the referenced branch.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>